version: 2

before:
  hooks:
    - go mod tidy

project_name: branch
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: darwin
        format: tar.gz
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
brews:
  - name: branch
    homepage: https://github.com/abroudoux/branch
    license: MIT
    commit_author:
      name: Arthur Broudoux
      email: arthur.broudoux@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: abroudoux
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_REPO_GITHUB_TOKEN }}"
