version: 2

before:
  hooks:
    - go mod tidy

project_name: branch
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: darwin
        format: tar.gz
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
