version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - go build -o bin/branch cmd/main.go

  run:
    desc: Run the app
    cmds:
      - task build
      - ./bin/branch {{ .CLI_ARGS }}
