version: "3"

tasks:
  run:
    desc: Run the app
    cmds:
      - GOGLAGS=-mod=mod go run branch.go

  build:
    desc: Build the app
    cmds:
      - GOGLAGS=-mod=mod go build -o branch branch.go

  clean:
    desc: Clean the app
    cmds:
      - rm -f dist
