version: "3"

tasks:
  build:
    desc: Build the binary
    cmds:
      - go build -o bin/branch cmd/branch.go

  dev:
    desc: Run the program in development mode
    deps: [build]
    cmds:
      - ./bin/branch {{ .CLI_ARGS }}

  rel:
    desc: Push a new release
    cmds:
      - git tag v{{ .CLI_ARGS }}
      - git push origin v{{ .CLI_ARGS }}
